"""complete_erp_domain

Revision ID: bfec8e166498
Revises: 0003
Create Date: 2026-08-14 12:18:14.530012
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bfec8e166498'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'key')
    )
    op.create_index(op.f('ix_document_sequences_hospital_id'), 'document_sequences', ['hospital_id'], unique=False)
    op.create_table('lab_vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'name')
    )
    op.create_index(op.f('ix_lab_vendors_hospital_id'), 'lab_vendors', ['hospital_id'], unique=False)
    op.create_table('procedure_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('name_am', sa.String(length=180), nullable=True),
    sa.Column('default_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'code')
    )
    op.create_index(op.f('ix_procedure_catalog_hospital_id'), 'procedure_catalog', ['hospital_id'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=180), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('member_number', sa.String(length=100), nullable=True),
    sa.Column('coverage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_hospital_id'), 'insurance_policies', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_insurance_policies_patient_id'), 'insurance_policies', ['patient_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('entry_number', sa.String(length=32), nullable=False),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('account', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=80), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_hospital_id'), 'ledger_entries', ['hospital_id'], unique=False)
    op.create_index('ix_ledger_hospital_posted', 'ledger_entries', ['hospital_id', 'posted_at'], unique=False)
    op.create_table('patient_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_documents_hospital_id'), 'patient_documents', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_patient_documents_patient_id'), 'patient_documents', ['patient_id'], unique=False)
    op.create_table('patient_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('condition', sa.String(length=180), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_histories_hospital_id'), 'patient_histories', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_patient_histories_patient_id'), 'patient_histories', ['patient_id'], unique=False)
    op.create_index('ix_patient_histories_patient_recorded', 'patient_histories', ['patient_id', 'recorded_at'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.String(length=140), nullable=True),
    sa.Column('license_number', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'employee_number')
    )
    op.create_index(op.f('ix_staff_hospital_id'), 'staff', ['hospital_id'], unique=False)
    op.create_index('ix_staff_hospital_name', 'staff', ['hospital_id', 'name'], unique=False)
    op.create_index(op.f('ix_staff_user_id'), 'staff', ['user_id'], unique=False)
    op.create_table('insurance_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('claim_number', sa.String(length=32), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'claim_number')
    )
    op.create_index(op.f('ix_insurance_claims_hospital_id'), 'insurance_claims', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_invoice_id'), 'insurance_claims', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_patient_id'), 'insurance_claims', ['patient_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_status'), 'insurance_claims', ['status'], unique=False)
    op.create_table('lab_order_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('lab_order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lab_order_id'], ['lab_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_order_events_hospital_id'), 'lab_order_events', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_lab_order_events_lab_order_id'), 'lab_order_events', ['lab_order_id'], unique=False)
    op.create_table('appointment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('old_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_events_appointment_id'), 'appointment_events', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_events_hospital_id'), 'appointment_events', ['hospital_id'], unique=False)
    op.create_table('clinical_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('dentist_id', sa.UUID(), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('examination', sa.Text(), nullable=False),
    sa.Column('vital_signs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dentist_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_assessments_appointment_id'), 'clinical_assessments', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_clinical_assessments_dentist_id'), 'clinical_assessments', ['dentist_id'], unique=False)
    op.create_index(op.f('ix_clinical_assessments_hospital_id'), 'clinical_assessments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_clinical_assessments_patient_id'), 'clinical_assessments', ['patient_id'], unique=False)
    op.create_table('treatment_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('note_type', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_notes_hospital_id'), 'treatment_notes', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_treatment_notes_patient_id'), 'treatment_notes', ['patient_id'], unique=False)
    op.create_table('dental_chart_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('tooth_number', sa.String(length=10), nullable=False),
    sa.Column('surfaces', sa.JSON(), nullable=False),
    sa.Column('condition', sa.String(length=80), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['clinical_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chart_patient_tooth', 'dental_chart_entries', ['patient_id', 'tooth_number'], unique=False)
    op.create_index(op.f('ix_dental_chart_entries_hospital_id'), 'dental_chart_entries', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_dental_chart_entries_patient_id'), 'dental_chart_entries', ['patient_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('tooth_number', sa.String(length=10), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['clinical_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_assessment_id'), 'diagnoses', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_hospital_id'), 'diagnoses', ['hospital_id'], unique=False)
    op.create_table('treatment_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('plan_number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('estimated_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['clinical_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'plan_number')
    )
    op.create_index(op.f('ix_treatment_plans_hospital_id'), 'treatment_plans', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_patient_id'), 'treatment_plans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_treatment_plans_status'), 'treatment_plans', ['status'], unique=False)
    op.create_table('treatment_plan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('treatment_plan_id', sa.UUID(), nullable=False),
    sa.Column('procedure_id', sa.UUID(), nullable=True),
    sa.Column('procedure_name', sa.String(length=180), nullable=False),
    sa.Column('tooth_number', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedure_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['treatment_plan_id'], ['treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_plan_items_hospital_id'), 'treatment_plan_items', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_treatment_plan_items_treatment_plan_id'), 'treatment_plan_items', ['treatment_plan_id'], unique=False)
    op.create_table('clinical_procedures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('treatment_plan_item_id', sa.UUID(), nullable=True),
    sa.Column('dentist_id', sa.UUID(), nullable=True),
    sa.Column('procedure_name', sa.String(length=180), nullable=False),
    sa.Column('tooth_number', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dentist_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['treatment_plan_item_id'], ['treatment_plan_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_procedures_hospital_id'), 'clinical_procedures', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_clinical_procedures_patient_id'), 'clinical_procedures', ['patient_id'], unique=False)
    op.create_table('dentist_commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('dentist_id', sa.UUID(), nullable=False),
    sa.Column('clinical_procedure_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('basis_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinical_procedure_id'], ['clinical_procedures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['staff.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dentist_commissions_dentist_id'), 'dentist_commissions', ['dentist_id'], unique=False)
    op.create_index(op.f('ix_dentist_commissions_hospital_id'), 'dentist_commissions', ['hospital_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source_procedure_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_procedure_id'], ['clinical_procedures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_due_at'), 'follow_ups', ['due_at'], unique=False)
    op.create_index(op.f('ix_follow_ups_hospital_id'), 'follow_ups', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_patient_id'), 'follow_ups', ['patient_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('clinical_procedure_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['clinical_procedure_id'], ['clinical_procedures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_hospital_id'), 'invoice_lines', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.add_column('appointments', sa.Column('dentist_id', sa.UUID(), nullable=True))
    op.add_column('appointments', sa.Column('priority', sa.String(length=20), server_default='NORMAL', nullable=False))
    op.add_column('appointments', sa.Column('chief_complaint', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('is_virtual', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('appointments', sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE appointments SET scheduled_end = scheduled_start + (duration_minutes * interval '1 minute')")
    op.alter_column('appointments', 'scheduled_end', nullable=False)
    op.add_column('appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_appointments_hospital_id_scheduled_start_0'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id_1'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status_2'), table_name='appointments')
    op.create_index(op.f('ix_appointments_dentist_id'), 'appointments', ['dentist_id'], unique=False)
    op.create_index('ix_appointments_hospital_start', 'appointments', ['hospital_id', 'scheduled_start'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_foreign_key(None, 'appointments', 'staff', ['dentist_id'], ['id'], ondelete='RESTRICT')
    op.add_column('expenses', sa.Column('vendor', sa.String(length=180), nullable=True))
    op.add_column('expenses', sa.Column('reference', sa.String(length=120), nullable=True))
    op.add_column('expenses', sa.Column('payment_method', sa.String(length=30), server_default='CASH', nullable=False))
    op.add_column('expenses', sa.Column('status', sa.String(length=30), server_default='POSTED', nullable=False))
    op.add_column('expenses', sa.Column('posted_by', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_expenses_hospital_id_incurred_at_0'), table_name='expenses')
    op.create_index('ix_expenses_hospital_incurred', 'expenses', ['hospital_id', 'incurred_at'], unique=False)
    op.create_foreign_key(None, 'expenses', 'users', ['posted_by'], ['id'], ondelete='SET NULL')
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=True))
    op.execute("UPDATE invoices SET subtotal = total_amount")
    op.alter_column('invoices', 'subtotal', nullable=False)
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_invoices_hospital_id_issued_at_0'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_patient_id_1'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status_2'), table_name='invoices')
    op.create_index('ix_invoices_hospital_issued', 'invoices', ['hospital_id', 'issued_at'], unique=False)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.add_column('lab_orders', sa.Column('vendor_id', sa.UUID(), nullable=True))
    op.add_column('lab_orders', sa.Column('shade', sa.String(length=40), nullable=True))
    op.add_column('lab_orders', sa.Column('tooth_numbers', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('lab_orders', sa.Column('instructions', sa.Text(), nullable=True))
    op.add_column('lab_orders', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lab_orders', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_lab_orders_hospital_id_due_date_0'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_patient_id_1'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_status_2'), table_name='lab_orders')
    op.create_index('ix_lab_orders_hospital_due', 'lab_orders', ['hospital_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_lab_orders_patient_id'), 'lab_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_status'), 'lab_orders', ['status'], unique=False)
    op.create_foreign_key(None, 'lab_orders', 'lab_vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.add_column('patients', sa.Column('father_name', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('grandfather_name', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('sub_city', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('woreda', sa.String(length=40), nullable=True))
    op.add_column('patients', sa.Column('kebele', sa.String(length=40), nullable=True))
    op.add_column('patients', sa.Column('landmark', sa.String(length=180), nullable=True))
    op.add_column('patients', sa.Column('preferred_language', sa.String(length=10), server_default='am', nullable=False))
    op.add_column('patients', sa.Column('medical_alerts', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('patients', sa.Column('allergies', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('patients', sa.Column('current_medications', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('patients', sa.Column('consent_to_treatment', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('patients', sa.Column('consent_to_sms', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('payments', sa.Column('reference', sa.String(length=120), nullable=True))
    op.add_column('payments', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('posted_by', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_payments_hospital_id_received_at_0'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id_2'), table_name='payments')
    op.drop_index(op.f('ix_payments_patient_id_1'), table_name='payments')
    op.create_index('ix_payments_hospital_received', 'payments', ['hospital_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_patient_id'), 'payments', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'users', ['posted_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_patient_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_index('ix_payments_hospital_received', table_name='payments')
    op.create_index(op.f('ix_payments_patient_id_1'), 'payments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_payments_invoice_id_2'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_hospital_id_received_at_0'), 'payments', ['hospital_id', 'received_at'], unique=False)
    op.drop_column('payments', 'posted_by')
    op.drop_column('payments', 'notes')
    op.drop_column('payments', 'reference')
    op.drop_column('patients', 'consent_to_sms')
    op.drop_column('patients', 'consent_to_treatment')
    op.drop_column('patients', 'current_medications')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'medical_alerts')
    op.drop_column('patients', 'preferred_language')
    op.drop_column('patients', 'landmark')
    op.drop_column('patients', 'kebele')
    op.drop_column('patients', 'woreda')
    op.drop_column('patients', 'sub_city')
    op.drop_column('patients', 'grandfather_name')
    op.drop_column('patients', 'father_name')
    op.drop_constraint(None, 'lab_orders', type_='foreignkey')
    op.drop_index(op.f('ix_lab_orders_status'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_patient_id'), table_name='lab_orders')
    op.drop_index('ix_lab_orders_hospital_due', table_name='lab_orders')
    op.create_index(op.f('ix_lab_orders_status_2'), 'lab_orders', ['status'], unique=False)
    op.create_index(op.f('ix_lab_orders_patient_id_1'), 'lab_orders', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_hospital_id_due_date_0'), 'lab_orders', ['hospital_id', 'due_date'], unique=False)
    op.drop_column('lab_orders', 'received_at')
    op.drop_column('lab_orders', 'sent_at')
    op.drop_column('lab_orders', 'instructions')
    op.drop_column('lab_orders', 'tooth_numbers')
    op.drop_column('lab_orders', 'shade')
    op.drop_column('lab_orders', 'vendor_id')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index('ix_invoices_hospital_issued', table_name='invoices')
    op.create_index(op.f('ix_invoices_status_2'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_patient_id_1'), 'invoices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_hospital_id_issued_at_0'), 'invoices', ['hospital_id', 'issued_at'], unique=False)
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'subtotal')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index('ix_expenses_hospital_incurred', table_name='expenses')
    op.create_index(op.f('ix_expenses_hospital_id_incurred_at_0'), 'expenses', ['hospital_id', 'incurred_at'], unique=False)
    op.drop_column('expenses', 'posted_by')
    op.drop_column('expenses', 'status')
    op.drop_column('expenses', 'payment_method')
    op.drop_column('expenses', 'reference')
    op.drop_column('expenses', 'vendor')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index('ix_appointments_hospital_start', table_name='appointments')
    op.drop_index(op.f('ix_appointments_dentist_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_status_2'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id_1'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_hospital_id_scheduled_start_0'), 'appointments', ['hospital_id', 'scheduled_start'], unique=False)
    op.drop_column('appointments', 'checked_out_at')
    op.drop_column('appointments', 'checked_in_at')
    op.drop_column('appointments', 'cancellation_reason')
    op.drop_column('appointments', 'scheduled_end')
    op.drop_column('appointments', 'is_virtual')
    op.drop_column('appointments', 'chief_complaint')
    op.drop_column('appointments', 'priority')
    op.drop_column('appointments', 'dentist_id')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_hospital_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_follow_ups_patient_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_hospital_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_due_at'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_dentist_commissions_hospital_id'), table_name='dentist_commissions')
    op.drop_index(op.f('ix_dentist_commissions_dentist_id'), table_name='dentist_commissions')
    op.drop_table('dentist_commissions')
    op.drop_index(op.f('ix_clinical_procedures_patient_id'), table_name='clinical_procedures')
    op.drop_index(op.f('ix_clinical_procedures_hospital_id'), table_name='clinical_procedures')
    op.drop_table('clinical_procedures')
    op.drop_index(op.f('ix_treatment_plan_items_treatment_plan_id'), table_name='treatment_plan_items')
    op.drop_index(op.f('ix_treatment_plan_items_hospital_id'), table_name='treatment_plan_items')
    op.drop_table('treatment_plan_items')
    op.drop_index(op.f('ix_treatment_plans_status'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_patient_id'), table_name='treatment_plans')
    op.drop_index(op.f('ix_treatment_plans_hospital_id'), table_name='treatment_plans')
    op.drop_table('treatment_plans')
    op.drop_index(op.f('ix_diagnoses_hospital_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_assessment_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_dental_chart_entries_patient_id'), table_name='dental_chart_entries')
    op.drop_index(op.f('ix_dental_chart_entries_hospital_id'), table_name='dental_chart_entries')
    op.drop_index('ix_chart_patient_tooth', table_name='dental_chart_entries')
    op.drop_table('dental_chart_entries')
    op.drop_index(op.f('ix_treatment_notes_patient_id'), table_name='treatment_notes')
    op.drop_index(op.f('ix_treatment_notes_hospital_id'), table_name='treatment_notes')
    op.drop_table('treatment_notes')
    op.drop_index(op.f('ix_clinical_assessments_patient_id'), table_name='clinical_assessments')
    op.drop_index(op.f('ix_clinical_assessments_hospital_id'), table_name='clinical_assessments')
    op.drop_index(op.f('ix_clinical_assessments_dentist_id'), table_name='clinical_assessments')
    op.drop_index(op.f('ix_clinical_assessments_appointment_id'), table_name='clinical_assessments')
    op.drop_table('clinical_assessments')
    op.drop_index(op.f('ix_appointment_events_hospital_id'), table_name='appointment_events')
    op.drop_index(op.f('ix_appointment_events_appointment_id'), table_name='appointment_events')
    op.drop_table('appointment_events')
    op.drop_index(op.f('ix_lab_order_events_lab_order_id'), table_name='lab_order_events')
    op.drop_index(op.f('ix_lab_order_events_hospital_id'), table_name='lab_order_events')
    op.drop_table('lab_order_events')
    op.drop_index(op.f('ix_insurance_claims_status'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_patient_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_invoice_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_hospital_id'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_index(op.f('ix_staff_user_id'), table_name='staff')
    op.drop_index('ix_staff_hospital_name', table_name='staff')
    op.drop_index(op.f('ix_staff_hospital_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index('ix_patient_histories_patient_recorded', table_name='patient_histories')
    op.drop_index(op.f('ix_patient_histories_patient_id'), table_name='patient_histories')
    op.drop_index(op.f('ix_patient_histories_hospital_id'), table_name='patient_histories')
    op.drop_table('patient_histories')
    op.drop_index(op.f('ix_patient_documents_patient_id'), table_name='patient_documents')
    op.drop_index(op.f('ix_patient_documents_hospital_id'), table_name='patient_documents')
    op.drop_table('patient_documents')
    op.drop_index('ix_ledger_hospital_posted', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_hospital_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_insurance_policies_patient_id'), table_name='insurance_policies')
    op.drop_index(op.f('ix_insurance_policies_hospital_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index(op.f('ix_procedure_catalog_hospital_id'), table_name='procedure_catalog')
    op.drop_table('procedure_catalog')
    op.drop_index(op.f('ix_lab_vendors_hospital_id'), table_name='lab_vendors')
    op.drop_table('lab_vendors')
    op.drop_index(op.f('ix_document_sequences_hospital_id'), table_name='document_sequences')
    op.drop_table('document_sequences')
    # ### end Alembic commands ###
